name: Python Selenium

on:
  push:
    branches:
      - main

env:
  APACHE_PORT: 80
  PYTHON_VERSION: 3.8
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Building Docker
      run: docker build -t my-apache2 .
    - name: Run Docker
      run: docker run -d -p 80:80 --name docker-apache -d my-apache2
    - name: Check Server
      run: curl http://localhost:80/index.php
    - name: Install Google Chrome
      run: |
            chmod +x ./InstallChrome.sh
            ./InstallChrome.sh
    
    - name: selenium script
      uses: actions/checkout@main
      with:
        repository: cap10jack/AUTng
        path: "./AUTng"
    - name: show working directory
      run: ls
    

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pip install selenium
        pip install pytest
        pip install webdriver-manager
    - name: run script
      run: |
            cd ./AUTng
            python test-selenium.py

